<a href="https://colab.research.google.com/github/DanIngrao/My-Python-Repository/blob/main/Practice15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np

In [15]:
array_unidim = np.array([1,2,3,4,5])

In [22]:
array_bidim = np.array([[1,2,3],
                        [4,5,6]])

In [26]:
array_tridim = np.array([[[1,2,3],
                         [4,5,6]],
                        [[7,8,9],
                        [10,11,12]]])

In [20]:
array_unidim.shape, array_unidim.ndim, array_unidim.dtype, array_unidim.size, type(array_unidim)

((5,), 1, dtype('int64'), 5, numpy.ndarray)

In [24]:
array_bidim.shape, array_bidim.ndim, array_bidim.dtype, array_bidim.size, type(array_bidim)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [27]:
array_tridim.shape, array_tridim.ndim, array_tridim.dtype, array_tridim.size, type(array_tridim)

((2, 2, 3), 3, dtype('int64'), 12, numpy.ndarray)

# ***Importamos Pandas***

In [29]:
import pandas as pd

datos = pd.DataFrame(array_bidim)
datos

0  1  2
0  1  2  3
1  4  5  6

# ***Creamos un array de 4x3 conformado por unos***

In [30]:
unos = np.ones((4,3))
unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# ***Creamos un array de 2x4x3, conformado unicamente por 0***

In [31]:
cero = np.zeros((2,4,3))
cero

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

# ***Creamos un array de numeros en el rango de 0 a 100, con un salto de 5***

In [33]:
array_1 = np.arange(0,101,5)
array_1

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

# ***Creamos un array de numeros aleatorios enteros comprendidos entre 0 y 10, de tamanio (2,5)***



In [34]:
array_2 = np.random.randint(0,10,(2,5))
array_2

array([[9, 4, 9, 6, 5],
       [2, 6, 2, 6, 6]])

# ***Creamos un array de numeros aleatorios decimales comprendidos entre 0 y 1, de tamanio (3,5)***

In [35]:
array_3 = np.random.random((3,5))
array_3

array([[0.05732706, 0.85531171, 0.40102903, 0.07052996, 0.43325307],
       [0.17585799, 0.40576823, 0.11257212, 0.74152058, 0.14766149],
       [0.93422118, 0.43638073, 0.5016321 , 0.92062362, 0.79389457]])

# ***Fijar semilla de random***

In [36]:
np.random.seed(27)

array_4 = np.random.randint(0,10,(3,5))
array_4

array([[3, 8, 8, 8, 0],
       [5, 8, 9, 1, 2],
       [1, 1, 4, 6, 3]])

# ***Encontrar elementos unicos del array_4***

In [37]:
np.unique(array_4)

array([0, 1, 2, 3, 4, 5, 6, 8, 9])

# ***Extraer del indice 1 del array_4***

In [38]:
array_4[1]

array([5, 8, 9, 1, 2])

# ***Extraer las primeras dos filas del array_4***

In [39]:
array_4[:2]

array([[3, 8, 8, 8, 0],
       [5, 8, 9, 1, 2]])

# ***Extraer los dos primeros datos de las primeras dos filas del array_4***

In [40]:
array_4[:2,:2]

array([[3, 8],
       [5, 8]])